notification_app_show_limit=3
notification_show_time=08:00
notification_show_hours_limit=24
need_to_show_notification=false
minus_one_page_app_packagename=in.amazon.mShop.android.shopping
config_tag_for_monetization_attribution=ro.channel.com.snapchat.android=SAMSUNG-INDIA-PRELOAD-20230721;ro.appsflyer.preinstall.path=/data/attribution/pre_install.appsflyer;io.branch.preinstall.apps.path=/data/attribution/pre_install_apps.branch